required = [
    "github.com/coreos/license-bill-of-materials"
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[override]]
name = "k8s.io/api"
revision = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/apiextensions-apiserver"
revision = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/apimachinery"
revision = "kubernetes-1.9.3"
[[constraint]]
name = "k8s.io/client-go"
revision = "kubernetes-1.9.3"

[[constraint]]
name = "github.com/coreos/etcd"
version = "v3.3.2"
[[constraint]]
name = "github.com/ghodss/yaml"
revision = "0ca9ea5df5451ffdf184b4428c902747c2c11cd7"
[[constraint]]
name = "github.com/golang/glog"
revision = "23def4e6c14b4da8ac2ed8007337bc5eb5007998"
[[constraint]]
name = "github.com/pborman/uuid"
revision = "ca53cad383cad2479bbba7f7a1a05797ec1386e4"
[[constraint]]
name = "github.com/spf13/cobra"
revision = "4cdb38c072b86bf795d2c81de50784d9fdd6eb77"
[[constraint]]
name = "golang.org/x/crypto"
revision = "0fe963104e9d1877082f8fb38f816fcd97eb1d10"
[[constraint]]
name = "google.golang.org/grpc"
version = "v1.10.0"

[[override]]
name = "github.com/coreos/license-bill-of-materials"
revision = "6e6186fc66ac0440c6d2302fbee89ede62c97831"
[[override]]
name = "github.com/davecgh/go-spew"
revision = "5215b55f46b2b919f50a1df0eaa5886afe4e3b3d"
[[override]]
name = "github.com/emicklei/go-restful"
revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"
[[override]]
name = "github.com/go-openapi/jsonpointer"
revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"
[[override]]
name = "github.com/go-openapi/jsonreference"
revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"
[[override]]
name = "github.com/go-openapi/spec"
revision = "6aced65f8501fe1217321abf0749d354824ba2ff"
[[override]]
name = "github.com/go-openapi/swag"
revision = "1d0bd113de87027671077d3c71eb3ac5d7dbba72"
[[override]]
name = "github.com/gogo/protobuf"
revision = "909568be09de550ed094403c2bf8a261b5bb730a"
[[override]]
name = "github.com/golang/protobuf"
revision = "4bd1920723d7b7c925de087aa32e2187708897f7"
[[override]]
name = "github.com/google/btree"
revision = "e89373fe6b4a7413d7acd6da1725b83ef713e6e4"
[[override]]
name = "github.com/google/gofuzz"
revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"
[[override]]
name = "github.com/googleapis/gnostic"
version = "v0.1.0"
[[override]]
name = "github.com/gregjones/httpcache"
revision = "2bcd89a1743fd4b373f7370ce8ddc14dfbd18229"
[[override]]
name = "github.com/hashicorp/golang-lru"
revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"
[[override]]
name = "github.com/howeyc/gopass"
revision = "bf9dde6d0d2c004a008c27aaee91170c786f6db8"
[[override]]
name = "github.com/imdario/mergo"
revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
[[override]]
name = "github.com/inconshreveable/mousetrap"
revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
[[override]]
name = "github.com/json-iterator/go"
version = "1.0.6"
[[override]]
name = "github.com/juju/ratelimit"
revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"
[[override]]
name = "github.com/mailru/easyjson"
revision = "d5b7844b561a7bc640052f1b935f7b800330d7e0"
[[override]]
name = "github.com/modern-go/concurrent"
revision = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
[[override]]
name = "github.com/modern-go/reflect2"
revision = "0b92968f4be75033e2089fba355a691ea2e9c5cc"
[[override]]
name = "github.com/petar/GoLLRB"
revision = "53be0d36a84c2a886ca057d34b6aa4468df9ccb4"
[[override]]
name = "github.com/peterbourgon/diskv"
version = "v2.0.1"
[[override]]
name = "github.com/PuerkitoBio/purell"
revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"
[[override]]
name = "github.com/PuerkitoBio/urlesc"
revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"
[[override]]
name = "github.com/spf13/pflag"
revision = "e57e3eeb33f795204c1ca35f56c44f83227c6e66"
[[override]]
name = "golang.org/x/net"
revision = "ae89d30ce0c63142b652837da33d782e2b0a9b25"
[[override]]
name = "golang.org/x/sys"
revision = "c28acc882ebcbfbe8ce9f0f14b9ac26ee138dd51"
[[override]]
name = "golang.org/x/text"
revision = "b7ef84aaf62aa3e70962625c80a571ae7c17cb40"
[[override]]
name = "google.golang.org/genproto"
revision = "df60624c1e9b9d2973e889c7a1cff73155da81c4"
[[override]]
name = "gopkg.in/inf.v0"
revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"
[[override]]
name = "gopkg.in/yaml.v2"
revision = "53feefa2559fb8dfa8d81baad31be332c97d6c77"
[[override]]
name = "k8s.io/kube-openapi"
revision = "275e2ce91dec4c05a4094a7b1daee5560b555ac9"
